spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/db_b105?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 960109

  jpa:
    databases-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

firebase:
  config:
    path: "D:/Project1/firebase-key/pjt-auth-97ed8-firebase-adminsdk-bniyn-80f0af0f6d.json"
    path2: "write your firebase-adminsdk-json to path"

image:
  path: "C:/viewment/images/"